### ISSUE TITLE
Support for KITTI

### ISSUE THREAD

**Issue by zmonoid** [qijiezhao/pytorch-ssd#2]
Hi, it seems that you have implemented KITTI for SSD and have some initial result.
May I know if you could release this part of model?

Best,
Bin

**Comment by qijiezhao** [comment]
Yeah,  we have achieved the 7th place of kitti car detection right now. 
[cfenet](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=2d)
But this part is our secret weapon recently.. we still want to get forward.  Maybe we will make it open after we get 1st.
