### ISSUE TITLE
how to compute 'min_sizes' and 'max_sizes'

### ISSUE THREAD

**Issue by isalirezag** [qijiezhao/pytorch-ssd#4]
can you please how you get the size of 'min_sizes' and 'max_sizes' in the config file?

**Comment by qijiezhao** [comment]
In my view, it's based on experience, which uses the large map to detect small objects and uses the small map to detect large objects. Then the problem comes to be: what range is large, is small? This step, you can totally define it yourself.

**Comment by Ontheway361** [comment]
emm, paper provide an advice for set min_sizes in formula (4) ...
